version: alpha
orbs:
  soos: soos-io/dast@dev:alpha # Get the latest version at https://circleci.com/developer/orbs/orb/soos-io/dast

workflows:
  main:
    jobs:
      - soos/run-dast-analysis:
          client_id: SOOS_CLIENT_ID
          api_key: SOOS_API_KEY
          project_name: dast-circleci-qa
          api_base_url: "https://qa-api.soos.io/api/"
          target_url: "https://joaquinalvarez.dev/"
          on_failure: "continue_on_failure"
          scan_mode: "baseline"
          
          
         
         
          

