version: 2.1
orbs:
  soos: soos-io/sca@1.0.13 # Get the latest version at https://circleci.com/developer/orbs/orb/soos-io/sca

workflows:
  main:
    jobs:
      - soos/sca-analysis:
          client_id: SOOS_CLIENT_ID
          api_key: SOOS_API_KEY
          project_name: sca-circleci-test
          api_base_url: 'https://qa-api.soos.io/api/'
          verbosity: "DEBUG"
          verbose: true
         
         
          

