version: 2.1

orbs:
  soos: soos-io/sca@x.y.z # Get the latest version at https://circleci.com/developer/orbs/orb/soos-io/sca

workflows:
  main:
    jobs:
      - soos/sca-analysis:
          client_id: "<<SOOS Client Id environment variable name. If it is SOOS_CLIENT_ID, there's no need to pass anything>>"
          api_key: "<<SOOS API Key environment variable name. If it is SOOS_API_KEY, there's no need to pass anything>>"
          project_name: "<<Project Name>>"
