version: 2.1
orbs:
  soos: soos-io/dast@alpha # Get the latest version at https://circleci.com/developer/orbs/orb/soos-io/dast

workflows:
  main:
    jobs:
      - soos/run-dast-analysis:
          client_id: SOOS_CLIENT_ID
          api_key: SOOS_API_KEY
          project_name: dast-circleci-qa
          target_url: 'https://qa-api.soos.io/api/'
          
          
         
         
          

